### ISSUE TITLE
The predicted value prediect_y is the same for all

### ISSUE THREAD

**Issue by zhantt626** [Marsrocky/EfficientFi#1]
Hello:
        Recently, I have been reading your article "EfficientFi: Toward Large-Scale Lightweight WiFi Sensing via CSI Compressio" and trying to implement the relevant code, but I encountered a problem in the process: The trained predicted value prediect_y is all the same value, which is inconsistent with the corresponding labels, resulting in the training error hovering around 1.78. After step by step inspection, it is found that the value of Loss2 is always around 1.78. I would like to ask if you have similar problems. Is there a solution? Thank you very much!

**Comment by Marsrocky** [comment]
This means that your model has not converged. You need to ensure that the classification loss is minimized, and the MSE loss decreases progressively.
